name: nvidia
distribution_spec:
  description: Use NVIDIA NIM for running LLM inference
  providers:
    inference: remote::nvidia
    memory: meta-reference
    safety: meta-reference
    agents: meta-reference
    telemetry: meta-reference
