services:
  nvidia-nim:
    image: nvcr.io/nim/meta/llama-3.1-8b-instruct:latest
    network_mode: "host"
    volumes:
      - $HOME/.cache/nim:/opt/nim/.cache
    ports:
      - "8000:8000"
    command: []
  llamastack:
    depends_on: 
    - nvidia-nim
    image: distribution-nvidia
    network_mode: "host"
    volumes:
      - ~/.llama:/root/.llama
      - ./run.yaml:/root/my-run.yaml
    ports:
      - "5000:5000"
    entrypoint: bash -c "sleep 60; python -m llama_stack.distribution.server.server --yaml_config /root/my-run.yaml"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
